import { NextRequest, NextResponse } from "next/server";
import { 
  supabase, 
  getSupabaseClient,
  toSupabase, 
  fromSupabase, 
  SupabaseProperty, 
  validateSessionUser, 
  sanitizeInput 
} from "@/lib/supabase";

function getSqlSchema() {
  return `
-- 1. Criar a tabela de propriedades rurais no SQL Editor do Supabase:
CREATE TABLE IF NOT EXISTS properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  municipality TEXT NOT NULL,
  reference_point TEXT,
  gps_coordinates TEXT,
  owner_name TEXT NOT NULL,
  cpf TEXT,
  birth_date TEXT,
  contact_phone TEXT,
  collaborative_owner BOOLEAN DEFAULT false,
  wifi_name TEXT,
  wifi_pass TEXT,
  residents JSONB DEFAULT '[]'::jsonb,
  photos JSONB DEFAULT '[]'::jsonb,
  last_patrol TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar RLS (Row Level Security):
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

-- 3. Criar uma política de acesso para que a chave anônima (anon) possa ler/escrever:
CREATE POLICY "Permitir acesso total público" 
ON properties FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);
  `.trim();
}

export async function GET(req: NextRequest) {
  try {
    // Hardening: Verify Supabase Session Token Server-side
    const user = await validateSessionUser(req);
    if (!user) {
      return NextResponse.json(
        { error: "unauthorized", message: "Não autorizado. Token de sessão inválido, ausente ou expirado." }, 
        { status: 401 }
      );
    }

    const supabaseClient = getSupabaseClient(req);

    const { searchParams } = new URL(req.url);
    const idParam = searchParams.get("id");

    if (idParam) {
      const id = parseInt(idParam, 10);
      if (isNaN(id)) {
        return NextResponse.json({ error: "ID inválido" }, { status: 400 });
      }

      const { data, error } = await supabaseClient
        .from("properties")
        .select("*")
        .eq("id", id)
        .single();

      if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 });
      }

      if (!data) {
        return NextResponse.json({ error: "Propriedade não encontrada" }, { status: 404 });
      }

      return NextResponse.json({ property: fromSupabase(data as SupabaseProperty) });
    }

    const q = searchParams.get("q");
    let queryBuilder = supabaseClient
      .from("properties")
      .select("id, name, municipality, reference_point, gps_coordinates, owner_name, collaborative_owner, last_patrol");

    if (q) {
      const searchStr = `%${q}%`;
      queryBuilder = queryBuilder.or(
        `name.ilike.${searchStr},municipality.ilike.${searchStr},owner_name.ilike.${searchStr},reference_point.ilike.${searchStr},cpf.ilike.${searchStr},contact_phone.ilike.${searchStr},wifi_name.ilike.${searchStr}`
      );
    }

    const { data, error } = await queryBuilder.order("id", { ascending: false });

    if (error) {
      // Check if table does not exist (relation error in Postgres is code 42P01)
      if (error.code === "42P01" || error.message?.includes('relation "properties" does not exist')) {
        return NextResponse.json(
          { 
            error: "table_missing", 
            message: "A tabela 'properties' não foi encontrada no banco de dados do Supabase.",
            sqlSchema: getSqlSchema()
          },
          { status: 404 }
        );
      }
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    const mapped = (data as SupabaseProperty[]).map(fromSupabase);
    return NextResponse.json({ properties: mapped });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    // Hardening: Verify Supabase Session Token Server-side
    const user = await validateSessionUser(req);
    if (!user) {
      return NextResponse.json(
        { error: "unauthorized", message: "Não autorizado. Token de sessão inválido, ausente ou expirado." }, 
        { status: 401 }
      );
    }

    const body = await req.json();
    const { property } = body;
    if (!property) {
      return NextResponse.json({ error: "Propriedade ausente no corpo" }, { status: 400 });
    }

    // Hardening: Server-side input validation & sanitization (prevents basic XSS & enforces schema limits)
    const sanitizedProperty = {
      ...property,
      name: sanitizeInput(property.name),
      municipality: sanitizeInput(property.municipality),
      referencePoint: sanitizeInput(property.referencePoint),
      gpsCoordinates: sanitizeInput(property.gpsCoordinates),
      ownerName: sanitizeInput(property.ownerName),
      cpf: sanitizeInput(property.cpf),
      birthDate: sanitizeInput(property.birthDate),
      contactPhone: sanitizeInput(property.contactPhone),
      wifiName: sanitizeInput(property.wifiName),
      wifiPass: sanitizeInput(property.wifiPass),
      lastPatrol: sanitizeInput(property.lastPatrol),
      residents: Array.isArray(property.residents) ? property.residents.map(sanitizeInput) : [],
      photos: Array.isArray(property.photos) ? property.photos.map(sanitizeInput) : [],
    };

    if (!sanitizedProperty.name || !sanitizedProperty.municipality || !sanitizedProperty.ownerName) {
      return NextResponse.json(
        { error: "Campos obrigatórios ausentes: nome da propriedade, município e proprietário são necessários." }, 
        { status: 400 }
      );
    }

    const sProp = toSupabase(sanitizedProperty);
    let result;
    const supabaseClient = getSupabaseClient(req);

    if (sProp.id) {
      // Update
      const { data, error } = await supabaseClient
        .from("properties")
        .upsert(sProp)
        .select();

      if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 });
      }
      result = data;
    } else {
      // Insert (omit ID to auto-increment)
      const { id, ...insertData } = sProp;
      const { data, error } = await supabaseClient
        .from("properties")
        .insert(insertData)
        .select();

      if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 });
      }
      result = data;
    }

    const saved = result && result.length > 0 ? fromSupabase(result[0]) : null;
    return NextResponse.json({ success: true, property: saved });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  try {
    // Hardening: Verify Supabase Session Token Server-side
    const user = await validateSessionUser(req);
    if (!user) {
      return NextResponse.json(
        { error: "unauthorized", message: "Não autorizado. Token de sessão inválido, ausente ou expirado." }, 
        { status: 401 }
      );
    }

    // Role-based access control: Only users with "admin" role or admin email can delete properties
    const role = user.app_metadata?.role || user.user_metadata?.role;
    const isAdmin = role === "admin" || user.email === "admin@patrulha.gov" || user.email?.startsWith("admin@");

    if (!isAdmin) {
      return NextResponse.json(
        { error: "Apenas usuários com perfil 'admin' podem excluir propriedades." },
        { status: 403 }
      );
    }

    const supabaseClient = getSupabaseClient(req);

    const { searchParams } = new URL(req.url);
    const clearAll = searchParams.get("clearAll");
    
    if (clearAll === "true") {
      const { error } = await supabaseClient
        .from("properties")
        .delete()
        .gt("id", 0);

      if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 });
      }

      return NextResponse.json({ success: true, message: "Todos os registros foram excluídos do Supabase." });
    }

    const idStr = searchParams.get("id");
    if (!idStr) {
      return NextResponse.json({ error: "ID ausente" }, { status: 400 });
    }

    const id = parseInt(idStr, 10);
    if (isNaN(id)) {
      return NextResponse.json({ error: "ID inválido" }, { status: 400 });
    }

    const { error } = await supabaseClient
      .from("properties")
      .delete()
      .eq("id", id);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
