import { NextRequest, NextResponse } from "next/server";
import { supabase, validateSessionUser } from "@/lib/supabase";

function getSqlSchema() {
  return `
-- 1. Criar a tabela de propriedades rurais no SQL Editor do Supabase:
CREATE TABLE IF NOT EXISTS properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  municipality TEXT NOT NULL,
  reference_point TEXT,
  gps_coordinates TEXT,
  owner_name TEXT NOT NULL,
  cpf TEXT,
  birth_date TEXT,
  contact_phone TEXT,
  collaborative_owner BOOLEAN DEFAULT false,
  wifi_name TEXT,
  wifi_pass TEXT,
  residents JSONB DEFAULT '[]'::jsonb,
  photos JSONB DEFAULT '[]'::jsonb,
  last_patrol TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar RLS (Row Level Security):
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

-- 3. Criar uma política de acesso para que a chave anônima (anon) possa ler/escrever:
CREATE POLICY "Permitir acesso total público" 
ON properties FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);
  `.trim();
}

export async function GET(req: NextRequest) {
  try {
    // Hardening: Verify Supabase Session Token Server-side
    const user = await validateSessionUser(req);
    if (!user) {
      return NextResponse.json(
        { error: "unauthorized", message: "Não autorizado. Token de sessão inválido, ausente ou expirado." }, 
        { status: 401 }
      );
    }

    const originalUrl = process.env.SUPABASE_URL || "https://frswlyctlykrnaorfoql.supabase.co/rest/v1/";
    const hasKeys = !!process.env.SUPABASE_URL && !!process.env.SUPABASE_ANON_KEY;

    // Run a quick query to test table existence and connection
    const { data, error } = await supabase
      .from("properties")
      .select("id")
      .limit(1);

    if (error) {
      if (error.code === "42P01" || error.message?.includes('relation "properties" does not exist')) {
        return NextResponse.json({
          connected: true,
          tableExists: false,
          supabaseUrl: originalUrl.replace(/\/rest\/v1\/?$/, ""),
          usingFallback: !hasKeys,
          sqlSchema: getSqlSchema(),
          message: "Conectado ao Supabase, mas a tabela 'properties' não existe. Por favor, crie-a no seu SQL Editor."
        });
      }

      return NextResponse.json({
        connected: false,
        tableExists: false,
        supabaseUrl: originalUrl.replace(/\/rest\/v1\/?$/, ""),
        usingFallback: !hasKeys,
        error: error.message,
        message: "Falha de conexão com o Supabase: " + error.message
      });
    }

    return NextResponse.json({
      connected: true,
      tableExists: true,
      supabaseUrl: originalUrl.replace(/\/rest\/v1\/?$/, ""),
      usingFallback: !hasKeys,
      message: "Conectado com sucesso ao Supabase!"
    });
  } catch (err: any) {
    return NextResponse.json({
      connected: false,
      tableExists: false,
      error: err.message,
      message: "Falha ao verificar status: " + err.message
    }, { status: 500 });
  }
}
